apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-config
data:
  application.properties: |-
    amq-broker-rhel8.allowed.channels[0]=7.10.x
    amq-broker-rhel8.allowed.channels[1]=7.11.x
    datagrid.allowed.channels[0]=8.3.x