apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.fullname" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "app.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.http.port }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.https.port }}
              protocol: TCP
          env:
          - name: QUARKUS_HTTP_SSL_CERTIFICATE_FILES
            value: /certs/tls.crt
          - name: QUARKUS_HTTP_SSL_CERTIFICATE_KEY_FILES
            value: /certs/tls.key
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
        #   resources:
# {{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - mountPath: /certs
            name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ template "app.fullname" . }}-serving-cert