apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "app.fullname" . }}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: {{ template "app.fullname" . }}.{{ .Release.Namespace }}.svc
    rules:
      - apiGroups:
          - operators.coreos.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - subscriptions
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "app.fullname" . }}
        path: /validate
    sideEffects: None
    failurePolicy: Ignore
    admissionReviewVersions:
      - v1